---
- name: install apache
  hosts: all
  become: true
  tasks:
    - name: Install Apache
      apt: name=apache2 update_cache=yes state=latest
      
    - name: Copy index test page
      template:
        src: "./index.html"
        dest: "/var/www/html/index.html"
  
  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
